### ISSUE TITLE
请问大佬脚本怎么用

### ISSUE THREAD

**Issue by QiHsMing** [ajouter/shiyi#2]
请问大佬，这个脚本怎么用（我没用注册到这个app），需要抓cookie吗？查了一下活动，第一天是刷脸实名后，后面几天就挂在青龙上就ok了吗？

**Comment by ajouter** [comment]
咔咔脚本？还是啥，网站上都有教程 http://bk.ajouter.cn



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月25日(周五) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ajouter/shiyi] 请问大佬脚本怎么用 (Issue #2)




 
请问大佬，这个脚本怎么用（我没用注册到这个app），需要抓cookie吗？查了一下活动，第一天是刷脸实名后，后面几天就挂在青龙上就ok了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by QiHsMing** [comment]
> 咔咔脚本？还是啥，网站上都有教程 http://bk.ajouter.cn
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月25日(周五) 下午4:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ajouter/shiyi] 请问大佬脚本怎么用 (Issue #2) 请问大佬，这个脚本怎么用（我没用注册到这个app），需要抓cookie吗？查了一下活动，第一天是刷脸实名后，后面几天就挂在青龙上就ok了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
